# Identificacion del proyecto en SonarQube.
sonar.projectKey=com.universidad:productos-service
sonar.projectName=Productos Service
sonar.projectVersion=1.0

# Rutas principales del codigo fuente y pruebas.
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes

# Integracion de cobertura generada por JaCoCo.
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# La clase principal se excluye para concentrar el analisis en la logica del laboratorio.
sonar.exclusions=**/*Application.java

# Servidor local de SonarQube levantado con Docker.
sonar.host.url=http://localhost:9000

# En este laboratorio el Quality Gate no bloquea la ejecucion local.
sonar.qualitygate.wait=false
